# Generated by Django 5.2 on 2025-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/img_box', verbose_name='Картинка аватара'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
    ]
